// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainerizeMigrate.Migrations;

#nullable disable

namespace TrainerizeMigrate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250203154625_changed table name to make references easier")]
    partial class changedtablenametomakereferenceseasier
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TrainerizeMigrate.Data.BodyWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("goal")
                        .HasColumnType("TEXT");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Body_Weight");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.CustomExcersize", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("alternateName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("new_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("recordType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("videoType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("videoUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Excerisize");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("CustomExcersizeid")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CustomExcersizeid");

                    b.ToTable("Tag");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.WeightPoint", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BodyWeightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("newbodystatid")
                        .HasColumnType("INTEGER");

                    b.Property<double>("value")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("BodyWeightId");

                    b.ToTable("Body_Weight_Point");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.Tag", b =>
                {
                    b.HasOne("TrainerizeMigrate.Data.CustomExcersize", null)
                        .WithMany("tags")
                        .HasForeignKey("CustomExcersizeid");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.WeightPoint", b =>
                {
                    b.HasOne("TrainerizeMigrate.Data.BodyWeight", null)
                        .WithMany("points")
                        .HasForeignKey("BodyWeightId");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.BodyWeight", b =>
                {
                    b.Navigation("points");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.CustomExcersize", b =>
                {
                    b.Navigation("tags");
                });
#pragma warning restore 612, 618
        }
    }
}
