// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TrainerizeMigrate.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("TrainerizeMigrate.Data.BodyWeight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("goal")
                        .HasColumnType("TEXT");

                    b.Property<string>("unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Body_Weight");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.WeightPoints", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("BodyWeightId")
                        .HasColumnType("TEXT");

                    b.Property<string>("date")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("value")
                        .HasColumnType("REAL");

                    b.HasKey("id");

                    b.HasIndex("BodyWeightId");

                    b.ToTable("Body_Weight_Point");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.WeightPoints", b =>
                {
                    b.HasOne("TrainerizeMigrate.Data.BodyWeight", null)
                        .WithMany("points")
                        .HasForeignKey("BodyWeightId");
                });

            modelBuilder.Entity("TrainerizeMigrate.Data.BodyWeight", b =>
                {
                    b.Navigation("points");
                });
#pragma warning restore 612, 618
        }
    }
}
